apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cosign-attach-sbom

spec:
  description: >-
    Attach an SBOM to a published image and store in a container registry
  params:
  - name: image
    description: Name (reference) of the container image
  - name: sbom-filename
    description: name of the SBOM file
  - name: cosign-image
    description: The cosign image to use
    default: 'gcr.io/projectsigstore/cosign:v0.6.0@sha256:2303322158802ec0452758578ac80801a3754ee9cb19c128fc5d1b2ec32fa2d2'

  workspaces:
  - name: input

  steps:
  - name: attach-sbom
    image: $(params.cosign-image)
    command:
    - /bin/cosign
    - attach
    - sbom
    - -sbom
    - $(workspaces.input.path)/$(params.sbom-filename)
    - $(params.image)

  - name: helpful-callout
    image: bash:latest
    script: |
      #!/usr/bin/env bash
      echo "Download the SBOM via:"
      echo "   cosign download sbom $(params.image)"