kind: Task
apiVersion: tekton.dev/v1beta1
metadata:
  name: secrets-quality-gate
spec:
  description: >-
    Fail if secrets were discovered in the scanned payload
  params:
    - name: sbom-filename
      description: The SBOM to search
  workspaces:
    - name: scan-target
      optional: true

  steps:
    - image: endeveit/docker-jq:latest
      name: quality-gate
      env:
        - name: REPORT_PATH
          value: $(workspaces.scan-target.path)/$(params.sbom-filename)
      script: |
        #!/usr/bin/env sh
        set -eu
        cat $REPORT_PATH | jq -r '.secrets // empty'

        if test -z "$(cat $REPORT_PATH | jq -r '.secrets // empty')" 
        then
            echo "PASS: no secrets found!"
        else
            echo "FAIL: secrets found!"
            exit 1
        fi
